# fly.toml app configuration file generated for dx-measure-api on 2024-04-27T14:59:17-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dx-measure-api'
primary_region = 'gru'

[build]
[build.args]
GO_VERSION = '1.22'

[env]
PORT = '3000'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
