name: Deploy API
on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
jobs:
  deploy:
    name: Deploy API
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: 'api'
          sparse-checkout-cone-mode: false

      - name: Move API files to root
        run: |
          ls -lah
          shopt -s dotglob
          mv api/* .
          rm -rf api
          ls -lah

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
